/**
 * Wasste never blurs the line between what it measured and what it modelled
 * (sections 11, 19 and 20). Every number on screen carries one of these.
 */
const VARIANTS = {
  measured: { label: 'Measured', title: 'Derived from recorded waste events and bin sensors.' },
  estimated: { label: 'Estimated', title: 'A modelled projection, not a measurement.' },
  simulated: { label: 'Simulated sensor data', title: 'This prototype has no hardware; sensor values are simulated.' },
  ai: { label: 'AI analysis', title: 'Generated by Gemini from the measured data.' },
  rules: { label: 'Rule-based', title: 'Generated by built-in rules because Gemini was unavailable.' },
  demo: { label: 'Demo result', title: 'No Gemini API key is configured, so this is a placeholder result.' },
};

export function SourceTag({ variant = 'measured', className = '', children }) {
  const meta = VARIANTS[variant] || VARIANTS.measured;

  return (
    <span
      title={meta.title}
      className={`inline-flex items-center gap-1 rounded border border-hairline px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-ink-muted ${className}`}
    >
      {children || meta.label}
    </span>
  );
}
